// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAufiBQJXVRX8dq2QtFaHIO5lArSYnbK8',
    appId: '1:981206625144:web:5747880db42598dc1f768d',
    messagingSenderId: '981206625144',
    projectId: 'fir-e-e1734',
    authDomain: 'fir-e-e1734.firebaseapp.com',
    storageBucket: 'fir-e-e1734.appspot.com',
    measurementId: 'G-LSMX8HFX1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTbSWNOOoM15R7NKmo1pu2Ss8AYtW2YG0',
    appId: '1:981206625144:android:b9fa7f12b43c131c1f768d',
    messagingSenderId: '981206625144',
    projectId: 'fir-e-e1734',
    storageBucket: 'fir-e-e1734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtGiQYRguJJ0gnS_39t9IIRpCBvip1LHI',
    appId: '1:981206625144:ios:26446e74bf2d869f1f768d',
    messagingSenderId: '981206625144',
    projectId: 'fir-e-e1734',
    storageBucket: 'fir-e-e1734.appspot.com',
    androidClientId: '981206625144-hcn0pkimvc8ob53d9nsq8g5tist2o2pl.apps.googleusercontent.com',
    iosClientId: '981206625144-7hauvsea260f3r0fp9qtaqqqfh92p562.apps.googleusercontent.com',
    iosBundleId: 'com.example.niketanstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtGiQYRguJJ0gnS_39t9IIRpCBvip1LHI',
    appId: '1:981206625144:ios:c6b92dae27d159361f768d',
    messagingSenderId: '981206625144',
    projectId: 'fir-e-e1734',
    storageBucket: 'fir-e-e1734.appspot.com',
    androidClientId: '981206625144-hcn0pkimvc8ob53d9nsq8g5tist2o2pl.apps.googleusercontent.com',
    iosClientId: '981206625144-o2hhdr4beg35c7s0oim1s18pgl4ilggv.apps.googleusercontent.com',
    iosBundleId: 'com.example.niketanstore.RunnerTests',
  );
}
